// <auto-generated />
using System;
using ExamOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamOnline.Migrations
{
    [DbContext(typeof(ExamOnlineContext))]
    [Migration("20250815034534_CreateDatabaseExam")]
    partial class CreateDatabaseExam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExamOnline.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ExamOnline.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExamName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("exam_name");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("level_id");

                    b.Property<string>("Pictures")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pictures");

                    b.Property<DateTime>("UpdatedUp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_up");

                    b.HasKey("ExamId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LevelId");

                    b.ToTable("exams");
                });

            modelBuilder.Entity("ExamOnline.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("level_id");

                    b.Property<string>("LevelName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("level_name");

                    b.HasKey("LevelId");

                    b.ToTable("levels");
                });

            modelBuilder.Entity("ExamOnline.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<string>("AnswerA")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("answer_A");

                    b.Property<string>("AnswerB")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("answer_B");

                    b.Property<string>("AnswerC")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("answer_C");

                    b.Property<string>("AnswerCorrect")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("answer_correct");

                    b.Property<string>("AnswerD")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("answer_D");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("ExamOnline.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("result_id");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("Score")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("score");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ResultId");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("results");
                });

            modelBuilder.Entity("ExamOnline.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ExamOnline.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PassWord")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pass_word");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ExamOnline.Models.Exam", b =>
                {
                    b.HasOne("ExamOnline.Models.Category", "Category")
                        .WithMany("Exams")
                        .HasForeignKey("CategoryId");

                    b.HasOne("ExamOnline.Models.Level", "Level")
                        .WithMany("Exams")
                        .HasForeignKey("LevelId");

                    b.Navigation("Category");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("ExamOnline.Models.Question", b =>
                {
                    b.HasOne("ExamOnline.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamOnline.Models.Result", b =>
                {
                    b.HasOne("ExamOnline.Models.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamId");

                    b.HasOne("ExamOnline.Models.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId");

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamOnline.Models.User", b =>
                {
                    b.HasOne("ExamOnline.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExamOnline.Models.Category", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ExamOnline.Models.Exam", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("ExamOnline.Models.Level", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ExamOnline.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExamOnline.Models.User", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
